//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUni.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckPoint
    {
        public CheckPoint()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int CheckPointId { get; set; }
        public string CheckPointName { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
    }
}
